[2024-07-18 20:51:42,571]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 20] - Started new program run.
[2024-07-18 20:51:42,571]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 21] - Initialized logging basic configuration.
[2024-07-18 20:57:16,520]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 20] - Started new program run.
[2024-07-18 20:57:16,520]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 21] - Initialized logging basic configuration.
[2024-07-18 20:58:00,771]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 20] - Started new program run.
[2024-07-18 20:58:00,899]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 21] - Initialized logging basic configuration.
[2024-07-18 21:04:45,977]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 20] - Started new program run.
[2024-07-18 21:04:45,977]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 21] - Initialized logging basic configuration.
[2024-07-18 21:05:06,759]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 20] - Started new program run.
[2024-07-18 21:05:06,764]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 21] - Initialized logging basic configuration.
[2024-07-18 21:05:08,319]: [ERROR]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 10] - Error while executing main.
Traceback (most recent call last):
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py", line 7, in main
    csvFileHelper = CsvFileHelper()
                    ^^^^^^^^^^^^^^^
TypeError: 'module' object is not callable. Did you mean: 'CsvFileHelper.CsvFileHelper(...)'?
[2024-07-18 21:05:08,320]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 12] - Exited program run.
[2024-07-18 21:05:39,140]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 20] - Started new program run.
[2024-07-18 21:05:39,140]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 21] - Initialized logging basic configuration.
[2024-07-18 21:05:40,491]: [ERROR]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 10] - Error while executing main.
Traceback (most recent call last):
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 32, in ReadFromCsvFile
    raise Exception(f'No valid csv file found at path "{filepath}".')
Exception: No valid csv file found at path "..\..\Rohdaten\flight_information.csv".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py", line 8, in main
    data = csvFileHelper.ReadFromCsvFile(Common.flightInfoFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 39, in ReadFromCsvFile
    raise Exception(f'Error while reading csv file "{filepath}".', e)
Exception: ('Error while reading csv file "..\\..\\Rohdaten\\flight_information.csv".', Exception('No valid csv file found at path "..\\..\\Rohdaten\\flight_information.csv".'))
[2024-07-18 21:05:40,493]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 12] - Exited program run.
[2024-07-18 21:06:05,394]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 20] - Started new program run.
[2024-07-18 21:06:05,394]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 21] - Initialized logging basic configuration.
[2024-07-18 21:06:06,553]: [ERROR]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 10] - Error while executing main.
Traceback (most recent call last):
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 32, in ReadFromCsvFile
    raise Exception(f'No valid csv file found at path "{filepath}".')
Exception: No valid csv file found at path "..\..\Rohdaten\flight_information.csv".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py", line 8, in main
    data = csvFileHelper.ReadFromCsvFile(Common.flightInfoFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 39, in ReadFromCsvFile
    raise Exception(f'Error while reading csv file "{filepath}".', e)
Exception: ('Error while reading csv file "..\\..\\Rohdaten\\flight_information.csv".', Exception('No valid csv file found at path "..\\..\\Rohdaten\\flight_information.csv".'))
[2024-07-18 21:06:06,556]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 12] - Exited program run.
[2024-07-18 21:07:53,395]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 20] - Started new program run.
[2024-07-18 21:07:53,395]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 21] - Initialized logging basic configuration.
[2024-07-18 21:07:54,680]: [ERROR]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 10] - Error while executing main.
Traceback (most recent call last):
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 31, in ReadFromCsvFile
    if (self.__IsFilePathValid(filepath) == False):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 18, in __IsFilePathValid
    if (isfile(filepath) == True and Path(filepath).suffix == Common.csvFileExtension):
                                                              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'Common' has no attribute 'csvFileExtension'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py", line 8, in main
    data = csvFileHelper.ReadFromCsvFile(Common.flightInfoFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 39, in ReadFromCsvFile
    raise Exception(f'Error while reading csv file "{filepath}".', e)
Exception: ('Error while reading csv file "..\\Rohdaten\\flight_information.csv".', AttributeError("module 'Common' has no attribute 'csvFileExtension'"))
[2024-07-18 21:07:54,682]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 12] - Exited program run.
[2024-07-18 21:08:05,553]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 20] - Started new program run.
[2024-07-18 21:08:05,554]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 21] - Initialized logging basic configuration.
[2024-07-18 21:08:06,930]: [ERROR]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 10] - Error while executing main.
Traceback (most recent call last):
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 31, in ReadFromCsvFile
    if (self.__IsFilePathValid(filepath) == False):
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 18, in __IsFilePathValid
    if (isfile(filepath) == True and Path(filepath).suffix == Common.csvFileExtension):
                                                              ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'Common' has no attribute 'csvFileExtension'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py", line 8, in main
    data = csvFileHelper.ReadFromCsvFile(Common.flightInfoFilePath)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py", line 39, in ReadFromCsvFile
    raise Exception(f'Error while reading csv file "{filepath}".', e)
Exception: ('Error while reading csv file "..\\Rohdaten\\flight_information.csv".', AttributeError("module 'Common' has no attribute 'csvFileExtension'"))
[2024-07-18 21:08:06,932]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 12] - Exited program run.
[2024-07-18 21:08:36,131]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 22] - Started new program run.
[2024-07-18 21:08:36,131]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 23] - Initialized logging basic configuration.
[2024-07-18 21:08:37,874]: [DEBUG]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py, LineNo: 36] - Successfully imported data from csv file "..\Rohdaten\flight_information.csv" of structure "(12017, 23)".
[2024-07-18 21:08:37,874]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 12] - Exited program run.
[2024-07-18 21:08:59,399]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 22] - Started new program run.
[2024-07-18 21:08:59,403]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 23] - Initialized logging basic configuration.
[2024-07-18 21:09:07,471]: [DEBUG]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py, LineNo: 36] - Successfully imported data from csv file "..\Rohdaten\flight_information.csv" of structure "(12017, 23)".
[2024-07-18 21:15:13,952]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 22] - Started new program run.
[2024-07-18 21:15:13,953]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 23] - Initialized logging basic configuration.
[2024-07-18 21:15:15,012]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\DataCleaner.py, LineNo: 14] - Reading flight info from file path "..\Rohdaten\flight_information.csv.
[2024-07-18 21:15:15,140]: [DEBUG]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py, LineNo: 36] - Successfully imported data from csv file "..\Rohdaten\flight_information.csv" of structure "(12017, 23)".
[2024-07-18 21:15:15,140]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\DataCleaner.py, LineNo: 16] - Reading ground info from file path "..\Rohdaten\ground_information.csv.
[2024-07-18 21:15:15,243]: [DEBUG]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py, LineNo: 36] - Successfully imported data from csv file "..\Rohdaten\ground_information.csv" of structure "(4173, 19)".
[2024-07-18 21:15:15,243]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 11] - Exited program run.
[2024-07-18 21:32:19,781]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 22] - Started new program run.
[2024-07-18 21:32:19,781]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\Common.py, LineNo: 23] - Initialized logging basic configuration.
[2024-07-18 21:32:22,198]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\DataCleaner.py, LineNo: 14] - Reading flight info from file path "..\Rohdaten\flight_information.csv.
[2024-07-18 21:32:22,538]: [DEBUG]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py, LineNo: 36] - Successfully imported data from csv file "..\Rohdaten\flight_information.csv" of structure "(12017, 23)".
[2024-07-18 21:32:22,539]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\DataCleaner.py, LineNo: 16] - Reading ground info from file path "..\Rohdaten\ground_information.csv.
[2024-07-18 21:32:22,599]: [DEBUG]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\CsvFileHelper.py, LineNo: 36] - Successfully imported data from csv file "..\Rohdaten\ground_information.csv" of structure "(4173, 19)".
[2024-07-18 21:32:22,600]: [INFO]	 - [D:\Dokumente\M.Sc._DataScience\Semester\3. Semester\3 - Fallstudie Model Engineering\Fallstudie\workspace\venv\main.py, LineNo: 11] - Exited program run.
